# npm-check-updates configuration used by yarn deps:check && yarn deps:update
# convenience scripts.
# @link https://github.com/raineorshine/npm-check-updates

# Add here exclusions on packages if any
reject: [
    "eslint",
    # To keep canary version for nextjs, ie "eslint-plugin-react-hooks": "^4.6.2 || ^5.0.0 || 5.0.0-canary-7118f5dd7-20230705",
    "eslint-plugin-react-hooks"
    #"@tanstack/eslint-plugin-query",
    #"@typescript-eslint/eslint-plugin",
    #"@typescript-eslint/parser",
    #"@typescript-eslint/typescript-estree",
    #"@typescript-eslint/utils",
  ]
