# npm-check-updates configuration used by yarn deps:check && yarn deps:update
# convenience scripts.
# @link https://github.com/raineorshine/npm-check-updates

cooldown: 1
reject: [
    # Till eslint v9 support
    "eslint",
    # till flat eslint 9 support
    "eslint-plugin-unicorn"
  ]
