changesetBaseRefs:
  - main
  - origin/main
  - upstream/main

changesetIgnorePatterns:
  - "**/*.test.{js,ts,jsx,tsx}"
  - "**/test.{js,ts,jsx,tsx}"
  - "**/*.spec.{js,ts,jsx,tsx}"

defaultSemverRangePrefix: ""

enableGlobalCache: false

enableScripts: false

nmMode: hardlinks-local

nodeLinker: node-modules

npmMinimalAgeGate: 4320

npmPreapprovedPackages:
  - "@flowblade/*"
  - "@httpx/*"
  - esbuild
  - "@esbuild/*"
  - "@typescript-eslint/*"
  - npm-check-updates
  - "@vitest/*"

npmPublishProvenance: true

npmRegistryServer: "https://registry.npmjs.org"
