module.exports = {
  graphqlSchema: require('./graphql-schema'),
  jest: require('./jest'),
  mdx: require('./mdx'),
  perfectionist: require('./perfectionist'),
  playwright: require('./playwright'),
  'prettier-config': require('./prettier-config'),
  'prettier-plugin': require('./prettier-plugin'),
  react: require('./react'),
  reactQuery: require('./react-query'),
  reactTestingLibrary: require('./rtl'),
  regexp: require('./regexp'),
  sonar: require('./sonar'),
  storybook: require('./storybook'),
  tailwind: require('./tailwind'),
  typescript: require('./typescript'),
};
