name: CI-monorepo-integrity

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - dev
      - main
    paths:
      - 'yarn.lock'
      - '.yarnrc.yml'
      - '.github/workflows/**'

  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - 'yarn.lock'
      - '.yarnrc.yml'
      - '.github/workflows/**'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24.x]
    steps:
      - uses: actions/checkout@v7

      - name: ⚙️ Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          package-manager-cache: false

      - name: 📥 Monorepo install
        uses: ./.github/actions/yarn-nm-install
        with:
          enable-corepack: 'true'

      - name: 👬🏽 Check for duplicate dependencies in lock file
        run: yarn dedupe --check

      - name: 🛟 Check monorepo dependency graph
        run: yarn check:install
